import { ArrowUpRight, Clock3, IndianRupee, PackageCheck, ShoppingCart, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";

const stats = [
  { label: "Orders today", value: "—", hint: "Waiting for WooCommerce", icon: ShoppingCart },
  { label: "Pending fulfilment", value: "—", hint: "Orders to process", icon: Clock3 },
  { label: "Revenue today", value: "—", hint: "Store currency", icon: IndianRupee },
  { label: "Customers", value: "—", hint: "From your store", icon: Users },
];

export default function Home() {
  return <AppShell><div className="space-y-8"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm text-muted-foreground">Today</p><h1 className="text-3xl font-semibold tracking-tight">Good evening.</h1><p className="mt-1 text-muted-foreground">Your WooCommerce operations at a glance.</p></div><a href="/settings" className="inline-flex w-fit items-center gap-2 rounded-lg border bg-background px-4 py-2 text-sm font-medium hover:bg-muted">Connect store <ArrowUpRight className="size-4" /></a></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => { const Icon = stat.icon; return <div key={stat.label} className="rounded-xl border bg-background p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{stat.label}</span><Icon className="size-4 text-muted-foreground" /></div><div className="mt-4 text-2xl font-semibold">{stat.value}</div><p className="mt-1 text-xs text-muted-foreground">{stat.hint}</p></div>; })}</section><section className="grid gap-4 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border bg-background p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recent orders</h2><p className="mt-1 text-sm text-muted-foreground">Live orders will appear here once the store is connected.</p></div><PackageCheck className="size-5 text-muted-foreground" /></div><div className="mt-10 rounded-lg border border-dashed p-10 text-center"><ShoppingCart className="mx-auto size-7 text-muted-foreground" /><p className="mt-3 text-sm font-medium">No orders loaded</p><p className="mt-1 text-sm text-muted-foreground">Connect WooCommerce to start managing orders from WooOps.</p></div></div><div className="rounded-xl border bg-background p-6 shadow-sm"><h2 className="font-semibold">Quick actions</h2><div className="mt-4 space-y-2"><a href="/orders" className="flex items-center justify-between rounded-lg border p-3 text-sm hover:bg-muted"><span>View all orders</span><ArrowUpRight className="size-4" /></a><a href="/products" className="flex items-center justify-between rounded-lg border p-3 text-sm hover:bg-muted"><span>Manage products</span><ArrowUpRight className="size-4" /></a><a href="/customers" className="flex items-center justify-between rounded-lg border p-3 text-sm hover:bg-muted"><span>Find a customer</span><ArrowUpRight className="size-4" /></a></div></div></section></div></AppShell>;
}
